words = ['over',
        'in front of',
        'beside',
        'on',
        'in',
        'attached to',
        'hanging from',
        'on back of',
        'falling off',
        'going down',
        'painted on',
        'walking on',
        'running on',
        'crossing',
        'standing on',
        'lying on',
        'sitting on',
        'flying over',
        'jumping over',
        'jumping from',
        'wearing',
        'holding',
        'carrying',
        'looking at',
        'guiding',
        'kissing',
        'eating',
        'drinking',
        'feeding',
        'biting',
        'catching',
        'picking',
        'playing with',
        'chasing',
        'climbing',
        'cleaning',
        'playing',
        'touching',
        'pushing',
        'pulling',
        'opening',
        'cooking',
        'talking to',
        'throwing',
        'slicing',
        'driving',
        'riding',
        'parked on',
        'driving on',
        'about to hit',
        'kicking',
        'swinging',
        'entering',
        'exiting',
        'enclosing',
        'leaning on',]
